### ISSUE TITLE
Function not creating Set

### ISSUE THREAD

**Issue by Entrebear** [MenEnger/dart_multiple_random_choice#1]
I am trying to use the randomMultipleWeightedChoice function to get a weighted random element as a result, from a Map of Strings and integers. However it does not seem to be creating the resulting Set. I am using the latest version of Flutter and package. When I try print the resulting set it doesn't show anything.

**Code**
```
String categorygen(Map<String, num> tempcatmap) {
  final tempset = randomMultipleWeightedChoice(tempcatmap, 1, null);
  print(tempset);
  final tempstring = tempset.elementAt(0);
  print(tempstring);
  return tempstring;
}
```

**Map that I'm passing in** (result of print of the Map)
`{cat1: 4, cat2: 2, cat3: 2, cat4: 3}`

**Error from console**
```
Bad state: No element

The relevant error-causing widget was: 
  Container Container:file:///C:/Apps/ /lib/pages/game.dart:145:18
When the exception was thrown, this was the stack: 
#0      Iterable.reduce (dart:core/iterable.dart:353:7)
#1      randomMultipleWeightedChoice (package:multiple_random_choice/multiple_random_choice.dart:25:67)
#2      categorygen (package: /models/game_mechanics.dart:47:19)
```

**Comment by MenEnger** [comment]
@Entrebear 
I apologize for the delay in seeing your comment. I will now check on this issue.

**Comment by MenEnger** [comment]
It was accidentally closed and has been reopened.

**Comment by MenEnger** [comment]
@Entrebear 
I tried to run the following code in my environment (Dart v2.17.6). 
It appears to be working correctly. 
I would like to test it with the latest Dart version at this time.

```dart
void debug1() {
  print('==debug1==');
  final Map<String, num> tempcatmap = {
    'cat1': 1,
    'cat2': 2,
    'cat3': 2,
    'cat4': 3
  };
  final tempset = randomMultipleWeightedChoice(tempcatmap, 1, null);
  print(tempset);
  final tempstring = tempset.elementAt(0);
  print(tempstring);
}
```

Result:
```
==debug1==
{cat3}
cat3
```
